src/objects/Care_Plan_Details__c.object
<CustomObject>
    <fields>
        <fullName>Active_Inactive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active Inactive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Care_Plan_Details</relationshipLabel>
        <relationshipName>Care_Plan_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Care Plan Details</label>
    <nameField>
        <label>Care Plan Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Care_Plan_Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TriggerCarePlanHandler.cls
public class TriggerCarePlanHandler {
    
    set<id> allContactIDs = new set<id>();
    List<Care_Plan_Details__c> allrelatedCarePlans = new List<Care_Plan_Details__c>();
    List<Care_Plan_Details__c> updateRecords = new List<Care_Plan_Details__c>();
    
  public void  UpdateActivestatus (List<Care_Plan_Details__c> Triggernew)
    {        
        for (Care_Plan_Details__c var : Triggernew)
        {
            allContactIDs.add(var.contact__c);
        }        
   	
       allrelatedCarePlans = [select id, Active_Inactive__c,contact__c from Care_Plan_Details__c where contact__c in:allContactIDs ];
     
       
       for (Care_Plan_Details__c var : allrelatedCarePlans) 
           {
                   Care_Plan_Details__c record = new Care_Plan_Details__c();
                    record.Id = var.id;
                    Record.Active_Inactive__c = false;
               updateRecords.add(record);               
           }
        
        if (!updateRecords.isEmpty())
        { 
            update updateRecords;
        }
    }
}